
services:
  web:
    build: .
    container_name: network-kewan-fr
    ports:
      - "8082:80"            # Accès au site sur http://localhost:8082
    volumes:
      - ./src:/var/www/html  # Pour live‑reload de votre code en développement